version: '3'

services:
  database:
    image: liyyt/mariadb:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: liyyt
    ports:
    - 3306:3306/tcp

